# Generated by Django 3.2.7 on 2021-09-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20210909_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image_thumb',
            new_name='image',
        ),
    ]
