# Generated by Django 3.2.7 on 2021-09-09 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_image_thumb_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='image',
            new_name='image_thumb',
        ),
    ]
