-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(S.SALES) as TOTAL_SALES
FROM BOOK_SALES S, BOOK B
WHERE S.BOOK_ID = B.BOOK_ID
  AND S.SALES_DATE BETWEEN TO_DATE('20220101', 'YYYYMMDD') AND TO_DATE('20220131', 'YYYYMMDD')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY