-- Oracle
SELECT CAR_ID, AVERAGE_DURATION
FROM (
    SELECT CAR_ID
        , ROUND(AVG(END_DATE - START_DATE + 1), 1) as AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)
WHERE AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- MySQL
SELECT a.CAR_ID, a.AVERAGE_DURATION
FROM (
    SELECT CAR_ID
        , ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) as AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) a
WHERE a.AVERAGE_DURATION >= 7
ORDER BY a.AVERAGE_DURATION DESC, a.CAR_ID DESC
